# Generated by Django 2.0 on 2018-03-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ypfcollection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField(default=0)),
                ('match_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
