# Generated by Django 2.0 on 2018-03-19 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ypfcollection', '0002_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ypfcollection.Player'),
        ),
    ]
