# Generated by Django 2.0 on 2018-03-19 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ypfcollection', '0003_auto_20180319_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='player_id',
            new_name='player',
        ),
    ]
